spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/booksdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      
      ddl-auto: update
  elasticsearch:
    uris:
      - http://localhost:9200

  kafka:

    bootstrap-servers: localhost:9092,localhost:9094,localhost:9095

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:

      group-id: book-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: "*"

        spring.json.value.default.type: backend.backend.events.BookEvent

server:
  port: 8081

debug: true
